name: eco_project
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^2.3.2
  salomon_bottom_bar: ^3.1.0
  google_maps_flutter: ^2.2.5
  camera: ^0.8.1+3
  image_picker: ^0.8.4+3
  image: ^3.0.2
  collection: ^1.16.0
  tflite_flutter: ^0.9.0
  tflite_flutter_helper:
      git:
        url: https://github.com/filofan1/tflite_flutter_helper.git
        ref: 783f15e5a87126159147d8ea30b98eea9207ac70

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  auto_route_generator: ^2.3.2
  build_runner: ^2.1.2
flutter:
  uses-material-design: true
  assets:
    - assets/photo_1.png
    - assets/photo_2.jpeg
    - assets/photo_3.jpeg
    - assets/photo_4.jpeg
    - assets/photo_5.jpeg
    - assets/photo_6.jpeg
    - assets/photo_map.png
    - assets/photo_camera.png
    - assets/map_style.json